// app/layout.tsx
<<<<<<< HEAD
import { Providers } from "./providers";
import type { Metadata } from "next";

=======
import type { Metadata } from "next";
>>>>>>> 85d3238e0ac3f12f942d25ace87a976b60e56442
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/context/ThemeContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

<<<<<<< HEAD
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <ThemeProvider>{children}</ThemeProvider>
          <Toaster position="top-right" />
        </Providers>
=======
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
        <ThemeProvider>{children}</ThemeProvider>
        <Toaster position="top-right" />
>>>>>>> 85d3238e0ac3f12f942d25ace87a976b60e56442
      </body>
    </html>
  );
}
