language: vi

# Optimize pipeline cho context recognition
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 150                # Tăng từ 100 → 150
  constrain_similarities: true
  entity_recognition: true
  intent_classification: true
- name: EntitySynonymMapper
- name: actions.components.entity_normalizer_component.EntityNormalizerComponent
- name: ResponseSelector
  epochs: 100

# Add entity extraction confidence
policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
    core_fallback_action_name: "action_default_fallback"
    core_fallback_threshold: 0.3
    nlu_threshold: 0.3
    enable_fallback_prediction: true

assistant_id: 20250702-182002-oblique-line
